format_version: 10
pipelines:
  My-New-Pipeline:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      test-repo:
        git: https://github.com/mariushilleke/own_tech_radar.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - log:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          log-greeting:
            timeout: 0
            environment_variables:
              test: test
            tasks:
            - exec:
                arguments:
                - $greeting
                command: echo
                run_if: passed
    parameters:
      greeting: hello
